services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service-local
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/auth_service?replicaSet=rs0
    ports:
      - '4001:4001'
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: auth-service-mongo-local
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  mongo_data:
